services:
  push:
    image: ghcr.io/worty/go-push:master
    build:
      context: .
    tmpfs:
      - /tmp
    environment:
      - TZ=Europe/Berlin
      - PUSHUSER=user
      - PUSHPW=password
      - HOST=https://push.worty.de
      - FORWARDSITE=https://worty.de
      - DATADIR=/data
    #cpus: 0.5
    mem_limit: 1G
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"